export const AllPermissions = {
  CREATE_USER: 'CREATE_USER',
  CREATE_COMPANY: 'CREATE_COMPANY',
  VALIDATE_COMPANY: 'VALIDATE_COMPANY',
  REJET_COMPANY: 'REJET_COMPANY',
  VIEW_COMPANY: 'VIEW_COMPANY',
  DELETE_COMPANY: 'DELETE_COMPANY',
  UPDATE_SELF_COMPANY: 'UPDATE_SELF_COMPANY',
  VIEW_SELF_COMPANY: 'VIEW_SELF_COMPANY',
  CREATE_OWNER: 'CREATE_OWNER',
  CREATE_DEVELOPER: 'CREATE_DEVELOPER',
  CREATE_PDG: 'CREATE_PDG',
  CREATE_DG: 'CREATE_DG',
  CREATE_ADG: 'CREATE_ADG',

  USER_MANAGER: 'USER_MANAGER',
  ROLE_MANAGER: 'ROLE_MANAGER',

  MANAGE_INSPECTION: 'MANAGE_INSPECTION',
} as const;
